version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .envs/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  admin:
    image: dpage/pgadmin4
    restart: always
    env_file:
    - .envs/pgadmin.env
    ports:
      - 8080:80
    volumes:
      - admin-data:/var/lib/pgadmin
volumes:
  db-data:
  admin-data:
